### ISSUE TITLE
consructors not building?

### ISSUE THREAD

**Issue by 0blubbel0** [TeamStarDrive/StarDrive#103]
like written in title I've got a problem with constructors.
I'm using blackbox with combined arms 8.3a and regardless if I build them manually or let the autobuilder run,
my space buildings won't be build!
Do the constructors need freighters now,too?
Pls help a confused player

**Comment by gkapulis** [comment]
hello, are you playing with large maps? are you using the latest bb build (815)?

**Comment by gkapulis** [comment]
Should be fixed in 14816. Let me know if it is not.
