### ISSUE TITLE
Tether StartingShip and Prototype to planet if they are  platforms or stations

### ISSUE THREAD

**Issue by gkapulis** [TeamStarDrive/StarDrive#131]
StartingShip and Prototype ships are defined per race in their XMLs. For instance:
`  <StartingShip>Wisp Fighter</StartingShip>`
`  <PrototypeShip>Draylok-Prototype</PrototypeShip>`

We need to tether these ships to the planet, after they are created, if they are Platforms Or Stations.

**Comment by SmischenkoB** [comment]
is it like prototype station?

**Comment by gkapulis** [comment]
There is no need to add more tags, the Prototype or Starting Ships can simply be stations, or platforms, if the modder wants to design them that way. We need to make sure they are simply tethered to the planet if they are orbitals

**Comment by SmischenkoB** [comment]
To be honest, it seems like that functionality is already there, because
there is function for tethering ship and it checks if it's station or not,
I will double check tomorrow morning

**Comment by gkapulis** [comment]
yeah, but i dont think its applied to starting ships. Hint - check CreateStartingShips()
