### ISSUE TITLE
Exception: Game.Run() failed, Unable to load DLL 'SDNative.dll'

### ISSUE THREAD

**Issue by Sylvus10** [TeamStarDrive/StarDrive#42]
(!) Exception: Game.Run() failed

Unable to load DLL 'SDNative.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Followed by: The type initializer for 'Ship_Game.Parallel' threw an exception.
Version = 1.41.14740 develop/commit
Mod = Vanilla
Language = English
StarDate = NULL
Ships = NULL
Planets = NULL
Memory = 1937
XnaMemory = 0
Thread = Main Thread
ThreadId = 1
Thread #1 Main Thread StackTrace:
   at Ship_Game.Parallel.GetPhysicalCPUCoreCount()
   at Parallel.InitThreadPool() in Threading\Parallel.cs:line 328
   at Parallel..cctor() in Threading\Parallel.cs:line 320
Followed by:
   at StarDriveGame..ctor() in GameScreens\StarDriveGame.cs:line 36
   at Program.Main(String[] args) in GameScreens\Program.cs:line 215

--------------------

Processor	12th Gen Intel(R) Core(TM) i5-12600K, 3700 Mhz, 10 Core(s), 16 Logical Processor(s)

**Comment by Sylvus10** [comment]
I did a clean install of the game from Steam. Local file path is C:\Program Files (x86)\Steam\steamapps\common\StarDrive.

**Comment by gkapulis** [comment]
if you install it on a the steam folder it wont work. you need to install it on a different path. [Check instruction](https://github.com/TeamStarDrive/StarDrive/releases/tag/mars-1.41.14664)s.

**Comment by Sylvus10** [comment]
Gotcha. Thank you!
