### ISSUE TITLE
Cannot launch 1.41.14776

### ISSUE THREAD

**Issue by Gen0** [TeamStarDrive/StarDrive#70]
I can't seem to load SD:BB at all. I have reinstalled XNA 3.1 and 4 to try and fix.

I am running the Arc A770 if it makes a difference. Please Help.

14:05:48.420ms: Loaded App Settings
14:05:48.501ms: 
 ======================================================
 ==== Mars : 1.41.14776 develop/commit             ====
 ==== UTC: 05/26/2023 14:05:48                     ====
 ======================================================

14:05:48.529ms: (!) Error: Sentry init failed: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
14:05:48.680ms: User=anon NET=4.0.30319.42000
14:05:48.680ms: GC Server=False LatencyMode=Batch
14:05:48.681ms: PhysicalCores=8 MaxParallelism=8
14:05:48.681ms: GameDir=C:\Program Files (x86)\Steam\steamapps\common\StarDrive
14:05:48.886ms: GraphicsDevice Disposing

**Comment by gkapulis** [comment]
Is the original game from steam working for you?

**Comment by Gen0** [comment]
It appears not. Sorry I didn't try since installing the new GPU.

![image_2023-05-26_165355329](https://github.com/TeamStarDrive/StarDrive/assets/747409/8512beb3-d0a8-4a80-b9b2-e1e951f5b081)

**Comment by gkapulis** [comment]
First. try to  uninstall stardrive completely and install only the steam version.
The error you see there is related to blackbox, not the original game.

**Comment by Gen0** [comment]
Stardrive vanilla works. On installing Blackbox with the installer exe I get the following crash on startup:

(!) Exception: Game.Run() failed

Unable to load DLL 'SDNative.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Followed by: The type initializer for 'Ship_Game.Parallel' threw an exception.
Version = 1.41.14776 develop/commit
Mod = Vanilla
Language = English
StarDate = NULL
Ships = NULL
Planets = NULL
Memory = 1419
XnaMemory = 0
Thread = Main Thread
ThreadId = 1
Thread #1 Main Thread StackTrace:
   at Ship_Game.Parallel.GetPhysicalCPUCoreCount()
   at Parallel.InitThreadPool() in Threading\Parallel.cs:line 328
   at Parallel..cctor() in Threading\Parallel.cs:line 320
Followed by:
   at StarDriveGame..ctor() in GameScreens\StarDriveGame.cs:line 36
   at Program.Main(String[] args) in GameScreens\Program.cs:line 215

**Comment by gkapulis** [comment]
you need to install bb+  in a directory which is not steam
Check the instructions in the major release page - https://github.com/TeamStarDrive/StarDrive/releases/tag/mars-1.41.14664

**Comment by Gen0** [comment]
Right so I installed SD to an external Steam folder now (as there is no way to install SD from steam into a custom folder).

It's now located at D:\SteamLibrary\steamapps\common\StarDrive

I also installed BB into C:\Games\StarDrivePlus

I get the same message when trying to start BB without native SD around it. I tried to copy the whole SD folder on top of the BB install location (skipping duplicate files) and I get the same error as above both times. I'll paste it here in case I missed a detail.

(!) Exception: Game.Run() failed

Unable to load DLL 'SDNative.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Followed by: The type initializer for 'Ship_Game.Parallel' threw an exception.
Version = 1.41.14776 develop/commit
Mod = Vanilla
Language = English
StarDate = NULL
Ships = NULL
Planets = NULL
Memory = 1419
XnaMemory = 0
Thread = Main Thread
ThreadId = 1
Thread #1 Main Thread StackTrace:
   at Ship_Game.Parallel.GetPhysicalCPUCoreCount()
   at Parallel.InitThreadPool() in Threading\Parallel.cs:line 328
   at Parallel..cctor() in Threading\Parallel.cs:line 320
Followed by:
   at StarDriveGame..ctor() in GameScreens\StarDriveGame.cs:line 36
   at Program.Main(String[] args) in GameScreens\Program.cs:line 215

I think the .14776 exe is a delta update seeing as the 14664 you just showed me is a lot bigger in filesize so I will install that and report back.

**Comment by gkapulis** [comment]
you need the big release file. not the 776 patch.
The patch will be installed by the auto patcher once your game (14664 installed on a non steam dir) works

**Comment by Gen0** [comment]
Yes I have it working now. I also found the bit in the release blurb that says that 14664 is the last major release.

User error, sorry and thanks for the help!

**Comment by gkapulis** [comment]
no problem. Let us know in discord how your games progress. We like to get feedback. :)
