### ISSUE TITLE
Is it possible to zoom in/out the size of in-game UI to fit for high resolution laptop screen? 

### ISSUE THREAD

**Issue by openipka** [TeamStarDrive/StarDrive#79]
Well, I'm running 1.41.14785 MARS, under 2560x1440 resolution and with my 17.3 inch screen on laptop, and it seems the UI in game is relatively small to see. 

![E{CTT(PX(Z7JTHCM_BXY`W0](https://github.com/TeamStarDrive/StarDrive/assets/78248875/8f852a53-fd3f-4899-89b8-f7b45b4ae7d6)

![)6MLIVT4`{Q Y85@NP`H`K4](https://github.com/TeamStarDrive/StarDrive/assets/78248875/e27fd203-c41c-42fe-a8cc-a94e219b3ec2)

I have tried different resolutions, and the size of the UI would change along with it. I think the size under 1920x1080 resolution is appropriate for my screen, but of course the game graphic would become somehow blurring due to the decrease of the resolution. 

So here's my question, is it possible to adjust the size of UI to fit for high resolution laptop screen without damaging the graphic? Like,  an adjustment bar to allow users to freely change the size of the UI？

**Comment by gkapulis** [comment]
It is rather complicated  in the current UI design. Indeed it looks too small. What i do is to run windowed mode on 1920x1080 or 1920x1200. Until we'll have time to address the design. 
@RedFox20

**Comment by gkapulis** [comment]
Using 1920X1080 or 1920X1200 is recommended for now.
